### PR TITLE
[BUG] Credit memos and refund payment appears in different order

### LINKED ISSUE #231: CreditMemos and RefundPayment appears in different order in admin order summary UI
image

Credit memos appearing not in the order they were made. I don't see how they sorted at all, possibly artifact of doctrine.
Refund payments are in correct order as they were made.

As there is not relation between credit memos and refund payment, we should at least try to sort them in same way

### PR DESCRIPTION
**Pull request by clem21**
Fixes #231

### CODE REVIEW

File: tests/Behat/Context/Ui/CreditMemoContext.php [hunk 1]
```diff
@@ -285,4 +285,11 @@ public function pdfFileShouldBeSuccessfullyDownloaded(): void
     {
         Assert::true($this->pdfDownloadElement->isPdfFileDownloaded());
     }
+
+    /**
+     * @Then /^I should see "([^"]+)" credit memo as (\d+)(?:|st|nd|rd|th) in the list/
+     */
+    public function iShouldCreditMemoOrderByAscInTheList(string $creditMemo, int $position): void {
+        Assert::true($this->creditMemoDetailsPage->isCreditMemoInPosition($creditMemo, $position));
+    }
```
Comment (arti0090) [inline tests/Behat/Context/Ui/CreditMemoContext.php:294]:
```suggestion
    public function iShouldCreditMemoOrderByAscInTheList(string $creditMemo, int $position): void 
    {
        Assert::true($this->creditMemoDetailsPage->isCreditMemoInPosition($creditMemo, $position));
    }
```

**Review by arti0090 — APPROVED** [review]

File: tests/Behat/Context/Ui/CreditMemoContext.php [hunk 2]
```diff
@@ -285,4 +285,11 @@ public function pdfFileShouldBeSuccessfullyDownloaded(): void
     {
         Assert::true($this->pdfDownloadElement->isPdfFileDownloaded());
     }
+
+    /**
+     * @Then /^I should see "([^"]+)" credit memo as (\d+)(?:|st|nd|rd|th) in the list/
```
Comment (AdamKasp) [inline tests/Behat/Context/Ui/CreditMemoContext.php:290]:
```suggestion
     * @Then /^I should see "([^"]+)" credit memo as (\d+)(?:|st|nd|rd|th) in the list$/
```

File: features/viewing_details_of_credit_memo.feature [hunk 3]
```diff
@@ -55,3 +55,11 @@ Feature: Viewing details of a credit memo
         And it should contain 1 "Galaxy Post" shipment with "4.50" gross value in "USD" currency
         And it should be issued in "United States" channel
         And its total should be "4.50" in "USD" currency
+
+    @ui
+    Scenario: Having all credit memos listed on the order page in ascending order
```
Comment (GSadee) [inline features/viewing_details_of_credit_memo.feature:60]: This file contains several scenarios for viewing details of credit memo, so this added scenario should be extracted to a separate feature file, sth like `seeing_credit_memos_on_admin_order_view.feature` to be consistent with others

File: features/viewing_details_of_credit_memo.feature [hunk 4]
```diff
@@ -55,3 +55,11 @@ Feature: Viewing details of a credit memo
...
+        Given the "#00000022" order's shipping cost already has a refund of "$4.50" with "Space money" payment
+        And the 1st "PHP T-Shirt" product from order "#00000022" has a refund of "$5.50" with "Space money" payment
+        When I view the summary of the order "#00000022"
+        Then I should see "4.50" credit memo as 1st in the list
+        And I should see "5.50" credit memo as 2nd in the list
```
Comment (GSadee) [inline features/viewing_details_of_credit_memo.feature:65]:
```suggestion
        Then I should see the credit memo with "$4.50" total as 1st in the list
        And I should see the credit memo with "$5.50" total as 2nd in the list
```

File: src/Doctrine/ORM/CreditMemoRepository.php [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+use Sylius\RefundPlugin\Repository\CreditMemoRepositoryInterface;
+
+class CreditMemoRepository extends EntityRepository implements CreditMemoRepositoryInterface
+{
+    public function findByOrderId(string $orderId): array
+    {
+        return $this->createQueryBuilder('c')
+            ->andWhere('c.order = :orderId')
+            ->addOrderBy('c.issuedAt', 'ASC')
+            ->setParameter('orderId', $orderId)
```
Comment (GSadee) [inline src/Doctrine/ORM/CreditMemoRepository.php:26]: In Sylius we have a convention to use `o` instead of `c`:
```suggestion
        return $this->createQueryBuilder('o')
            ->andWhere('o.order = :orderId')
            ->addOrderBy('o.issuedAt', 'ASC')
            ->setParameter('orderId', $orderId)
```

File: tests/Behat/Page/Admin/CreditMemoDetailsPage.php [hunk 6]
```diff
@@ -126,13 +126,24 @@ public function getToAddress(): string
...
+    }
+
     protected function getDefinedElements(): array
     {
         return array_merge(parent::getDefinedElements(), [
             'table' => 'table',
             'tax_item_amount' => 'tr.tax-item:contains("%label%") .tax-item-amount',
             'total' => '#credit-memo-total',
             'total_currency_code' => '#credit-memo-total-currency-code',
+            'credit_memo_in_given_position' => 'table tbody tr:nth-child(%position%) td:contains("%creditMemo%")',
```
Comment (GSadee) [inline tests/Behat/Page/Admin/CreditMemoDetailsPage.php:146]: Wrong order of keys in the array (should be alphabetical)

File: tests/Behat/Context/Ui/CreditMemoContext.php [hunk 7]
```diff
@@ -285,4 +285,12 @@ public function pdfFileShouldBeSuccessfullyDownloaded(): void
     {
         Assert::true($this->pdfDownloadElement->isPdfFileDownloaded());
     }
+
+    /**
+     * @Then /^I should see "([^"]+)" credit memo as (\d+)(?:|st|nd|rd|th) in the list$/
+     */
+    public function iShouldCreditMemoOrderByAscInTheList(string $creditMemo, int $position): void
```
Comment (GSadee) [inline tests/Behat/Context/Ui/CreditMemoContext.php:292]:
```suggestion
    public function iShouldCreditMemoOrderByAscInTheList(string $creditMemoTotal, int $position): void
```

File: features/seeing_refund_payments_on_admin_order_view.feature [hunk 8]
```diff
@@ -26,3 +26,10 @@ Feature: Seeing refund payments on admin order view
     Scenario: Seeing refund payment on order view
         When I view the summary of the order "#00000022"
         Then I should see 1 refund payment with status "New"
+
+    @ui
+    Scenario: Having all credit memos listed on the order page in ascending order
```
Comment (GSadee) [inline features/seeing_refund_payments_on_admin_order_view.feature:31]: Still, I would be for extracting this scenario to a separate file, because credit memo is a different entity than refund payment and doesn't fit this feature file

File: tests/Behat/Page/Admin/CreditMemoDetailsPage.php [hunk 9]
```diff
@@ -126,9 +126,20 @@ public function getToAddress(): string
...
     }
 
+    public function isCreditMemoInPosition(string $creditMemo, int $position): bool
+    {
+        $result = $this->getElement('credit_memo_in_given_position', [
+            '%position%' => $position,
+            '%creditMemo%' => $creditMemo,
+        ]);
+
+        return $result !== null;
```
Comment (GSadee) [inline tests/Behat/Page/Admin/CreditMemoDetailsPage.php:136]: I guess it should work:
```suggestion
        return $this->hasElement('credit_memo_in_given_position', [
            '%position%' => $position,
            '%creditMemo%' => $creditMemo,
        ]);
```

File: features/seeing_refund_payments_on_admin_order_view.feature (hunk 8 above)
Comment (clem21) [reply features/seeing_refund_payments_on_admin_order_view.feature:31]: There's been a misunderstanding, I thought you said to put it in this file, I'm going to create a new one then

File: features/seeing_refund_payments_on_admin_order_view.feature [hunk 10]
```diff
@@ -26,3 +26,4 @@ Feature: Seeing refund payments on admin order view
     Scenario: Seeing refund payment on order view
         When I view the summary of the order "#00000022"
         Then I should see 1 refund payment with status "New"
+
```
Comment (GSadee) [inline features/seeing_refund_payments_on_admin_order_view.feature:29]:
```suggestion
```

File: features/seeing_credit_memos_on_admin_order_view.feature [hunk 11]
```diff
@@ -0,0 +1,27 @@
...
+    And the store has a product "PHP T-Shirt" priced at "$10.00"
+    And the store has a product "Symfony Mug" priced at "$21.00"
+    And there is a customer "rick.sanchez@wubba-lubba-dub-dub.com" that placed an order "#00000022"
+    And the customer bought a "PHP T-Shirt" and a "Symfony Mug"
+    And the customer "Rick Sanchez" addressed it to "Seaside Fwy", "90802" "Los Angeles" in the "United States" with identical billing address
+    And the customer chose "Galaxy Post" shipping method with "Space money" payment
+    And the order "#00000022" is already paid
+    And I am logged in as an administrator
+
+
```
Comment (GSadee) [inline features/seeing_credit_memos_on_admin_order_view.feature:20]:
```suggestion
```

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, Clémence! :1st_place_medal:

File: features/seeing_refund_payments_on_admin_order_view.feature (hunk 10 above)
Comment (clem21) [reply features/seeing_refund_payments_on_admin_order_view.feature:29]: Fixed here https://github.com/Sylius/RefundPlugin/pull/243

Comment (Tomanhez) [inline features/seeing_refund_payments_on_admin_order_view.feature:29]: Redundant blank line

File: tests/Behat/Context/Ui/CreditMemoContext.php [hunk 12]
```diff
@@ -285,4 +285,12 @@ public function pdfFileShouldBeSuccessfullyDownloaded(): void
     {
         Assert::true($this->pdfDownloadElement->isPdfFileDownloaded());
     }
+
+    /**
+     * @Then /^I should see the credit memo with "([^"]+)" total as (\d+)(?:|st|nd|rd|th) in the list$/
+     */
+    public function iShouldCreditMemoOrderByAscInTheList(string $creditMemoTotal, int $position): void
```
Comment (Tomanhez) [inline tests/Behat/Context/Ui/CreditMemoContext.php:292]: iShouldSeeTheCreditMemoWithTotalAsInTheList
