### PR TITLE
Refunding shipments with taxes

### LINKED ISSUE #110: Bug with tax and shipments
When calculating refunds on shipments, there are 3 bugs : 

1. Only first shipment is refunded (it fails if you have multiple shipments)
2. Tax is not applied actually
3. Order shipping promotion adjustment is not refunded

**About which tax to apply.**
For each unit you already rebuild tax from order item unit data (and not from variant/product/zone matching). That works but for shipments that's not working as long tax of each shipment is not stored per shipment adjustment but on a single order shipping adjustment, you should sum all shipment adjustement and calculate tax ratio with tax adjustment linked to the order to find which tax has been applied to a shipment.

_(That will fail in case of multiple shipments with different tax on each shipments but I'm not sure it's really a use case in the context of a single order.)_

### PR DESCRIPTION
**Pull request by GSadee**
Partially fixes #110

### CODE REVIEW

File: src/TaxesApplicator/OrderItemsTaxesApplicator.php [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+            foreach ($item->getUnits() as $unit) {
+                if (0 === $splitTaxes[$i]) {
+                    continue;
+                }
+
+                $this->addAdjustment($unit, $splitTaxes[$i], $taxRate);
+                ++$i;
+            }
+        }
+    }
```
Comment (arti0090) [inline src/TaxesApplicator/OrderItemsTaxesApplicator.php:89]:
```suggestion
            /** @var OrderItemUnitInterface $unit */
            foreach ($item->getUnits() as $index => $unit) {
                if (0 === $splitTaxes[$index]) {
                    continue;
                }

                $this->addAdjustment($unit, $splitTaxes[$i], $taxRate);
            }
        }
    }
```
🙃

**Review by arti0090 — APPROVED** [review]

File: src/TaxesApplicator/OrderItemsTaxesApplicator.php (hunk 1 above)
Comment (GSadee) [reply src/TaxesApplicator/OrderItemsTaxesApplicator.php:89]: I agree, it looks better and as this is a duplicate service from Sylius, I invite you to correct it there 😃

**Review by AdamKasp — APPROVED** [review]

File: spec/OrderProcessor/OrderTaxesProcessorSpec.php [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+        TaxCalculationStrategyInterface $strategyOne,
+        TaxCalculationStrategyInterface $strategyTwo
+    ): void {
+        $order->getItems()->willReturn(new ArrayCollection([$orderItem->getWrappedObject()]));
+        $order->getShipments()->willReturn(new ArrayCollection([$shipment->getWrappedObject()]));
+        $order->isEmpty()->willReturn(false);
+        $order->getBillingAddress()->willReturn($address);
+
+        $order->removeAdjustments(AdjustmentInterface::TAX_ADJUSTMENT)->shouldBeCalled();
+        $orderItem->removeAdjustmentsRecursively(AdjustmentInterface::TAX_ADJUSTMENT)->shouldBeCalled();
```
Comment (Tomanhez) [inline spec/OrderProcessor/OrderTaxesProcessorSpec.php:64]:
```suggestion
        $order->getItems()->willReturn(new ArrayCollection([$orderItem->getWrappedObject()]));
        $order->getShipments()->willReturn(new ArrayCollection([$shipment->getWrappedObject()]));
        $order->isEmpty()->willReturn(false);
        $order->getBillingAddress()->willReturn($address);
        $order->removeAdjustments(AdjustmentInterface::TAX_ADJUSTMENT)->shouldBeCalled();
        
        $orderItem->removeAdjustmentsRecursively(AdjustmentInterface::TAX_ADJUSTMENT)->shouldBeCalled();
```

Here and below

File: spec/OrderProcessor/OrderTaxesProcessorSpec.php [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+    }
+
+    function it_does_not_process_taxes_if_there_is_no_order_item(OrderInterface $order): void
+    {
+        $order->removeAdjustments(AdjustmentInterface::TAX_ADJUSTMENT)->shouldBeCalled();
+        $order->getItems()->willReturn(new ArrayCollection([]));
+        $order->getShipments()->willReturn(new ArrayCollection([]));
+        $order->isEmpty()->willReturn(true);
+
+        $order->getBillingAddress()->shouldNotBeCalled();
```
Comment (Tomanhez) [inline spec/OrderProcessor/OrderTaxesProcessorSpec.php:113]:
```suggestion
        $order->isEmpty()->willReturn(true);
        $order->getBillingAddress()->shouldNotBeCalled();
```

File: spec/TaxesApplicator/OrderItemUnitsTaxesApplicatorSpec.php [hunk 4]
```diff
@@ -0,0 +1,209 @@
...
+        ZoneInterface $zone
+    ): void {
+        $order->getItems()->willReturn($items);
+
+        $items->count()->willReturn(2);
+        $items->getIterator()->willReturn(new \ArrayIterator([$orderItem->getWrappedObject()]));
+
+        $orderItem->getQuantity()->willReturn(2);
+
+        $orderItem->getVariant()->willReturn($productVariant);
```
Comment (Tomanhez) [inline spec/TaxesApplicator/OrderItemUnitsTaxesApplicatorSpec.php:191]:
```suggestion
        $orderItem->getQuantity()->willReturn(2);
        $orderItem->getVariant()->willReturn($productVariant);
```

File: spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php [hunk 5]
```diff
@@ -0,0 +1,205 @@
...
+        ZoneInterface $zone
+    ): void {
+        $order->getItems()->willReturn($items);
+
+        $items->count()->willReturn(1);
+        $items->getIterator()->willReturn(new \ArrayIterator([$orderItem->getWrappedObject()]));
+
+        $orderItem->getQuantity()->willReturn(2);
+
+        $orderItem->getVariant()->willReturn($productVariant);
```
Comment (Tomanhez) [inline spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php:72]:
```suggestion
        $orderItem->getQuantity()->willReturn(2);
        $orderItem->getVariant()->willReturn($productVariant);
```

File: spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php [hunk 6]
```diff
@@ -0,0 +1,205 @@
...
+        OrderInterface $order,
+        OrderItemInterface $orderItem,
+        ProductVariantInterface $productVariant,
+        ZoneInterface $zone
+    ): void {
+        $order->getItems()->willReturn($items);
+
+        $items->count()->willReturn(1);
+        $items->getIterator()->willReturn($iterator);
+        $iterator->rewind()->shouldBeCalled();
```
Comment (Tomanhez) [inline spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php:147]:
```suggestion
        $items->getIterator()->willReturn($iterator);
        
        $iterator->rewind()->shouldBeCalled();
```

File: spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php [hunk 7]
```diff
@@ -0,0 +1,205 @@
...
+        $iterator->valid()->willReturn(true, false)->shouldBeCalled();
+        $iterator->current()->willReturn($orderItem);
+        $iterator->next()->shouldBeCalled();
+
+        $orderItem->getQuantity()->willReturn(5);
+
+        $orderItem->getVariant()->willReturn($productVariant);
```
Comment (Tomanhez) [inline spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php:154]:
```suggestion
        $orderItem->getQuantity()->willReturn(5);
        $orderItem->getVariant()->willReturn($productVariant);
```

File: spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+        CalculatorInterface $calculator,
+        TaxRateResolverInterface $taxRateResolver,
+        OrderInterface $order,
+        ShipmentInterface $shipment,
+        ShippingMethodInterface $shippingMethod,
+        ZoneInterface $zone
+    ): void {
+        $order->getShippingTotal()->willReturn(100);
+        $order->getShipments()->willReturn(new ArrayCollection([$shipment->getWrappedObject()]));
+        $shipment->getMethod()->willReturn($shippingMethod);
```
Comment (Tomanhez) [inline spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php:140]:
```suggestion
        $order->getShipments()->willReturn(new ArrayCollection([$shipment->getWrappedObject()]));
        
        $shipment->getMethod()->willReturn($shippingMethod);
```

File: src/DependencyInjection/SyliusRefundExtension.php [hunk 9]
```diff
@@ -48,7 +48,10 @@ public function prepend(ContainerBuilder $container): void
 
         $container->prependExtensionConfig('sylius_labs_doctrine_migrations_extra', [
             'migrations' => [
-                'Sylius\RefundPlugin\Migrations' => ['Sylius\Bundle\CoreBundle\Migrations'],
+                'Sylius\RefundPlugin\Migrations' => [
+                    'Sylius\Bundle\CoreBundle\Migrations',
+                    'Sylius\Bundle\AdminApiBundle\Migrations',
+                ],
```
Comment (Tomanhez) [inline src/DependencyInjection/SyliusRefundExtension.php:54]: Maybe we should add functional test for this?

File: src/Migrations/Version20201208105207.php [hunk 10]
```diff
@@ -0,0 +1,109 @@
...
+    }
+
+    private function setDefaultAdjustmentData(): void
+    {
+        $this->connection->executeQuery("UPDATE sylius_adjustment SET shipment_id = null, details = '[]'");
+    }
+
+    private function updateAdjustment(int $adjustmentId, string $shipmentId, string $details): void
+    {
+        $this->connection->executeQuery("UPDATE sylius_adjustment SET shipment_id = $shipmentId, details = '" . $details . "' WHERE id = $adjustmentId");
```
Comment (lchrusciel) [inline src/Migrations/Version20201208105207.php:92]: Why did you decide for query execution instead of addSql? I would have to dig into it, but IIRC `addSql` is a good practice with the doctrine migrations

File: src/OrderProcessor/ShippingChargesProcessor.php [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+    {
+        /** @var OrderInterface $order */
+        Assert::isInstanceOf($order, OrderInterface::class);
+
+        // Remove all shipping adjustments, we recalculate everything from scratch.
+        $order->removeAdjustments(AdjustmentInterface::SHIPPING_ADJUSTMENT);
+
+        /** @var ShipmentInterface $shipment */
+        foreach ($order->getShipments() as $shipment) {
+            $shipment->removeAdjustments(AdjustmentInterface::SHIPPING_ADJUSTMENT);
```
Comment (lchrusciel) [inline src/OrderProcessor/ShippingChargesProcessor.php:58]: Do we really need both removals?

File: src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php [hunk 12]
```diff
@@ -0,0 +1,91 @@
...
+use Sylius\Component\Taxation\Resolver\TaxRateResolverInterface;
+use Sylius\RefundPlugin\Entity\AdjustmentInterface;
+
+/**
+ * @internal
+ *
+ * This class is not covered by the backward compatibility promise and it will be removed after update Sylius to 1.9.
+ * It is a duplication of a logic from Sylius to provide proper adjustments handling.
+ */
+class OrderItemUnitsTaxesApplicator implements OrderTaxesApplicatorInterface
```
Comment (lchrusciel) [inline src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php:32]: Missing final or on purpose? 
```suggestion
final class OrderItemUnitsTaxesApplicator implements OrderTaxesApplicatorInterface
```

File: src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php [hunk 13]
```diff
@@ -0,0 +1,91 @@
...
+            AdjustmentInterface::TAX_ADJUSTMENT,
+            $taxRate->getLabel(),
+            $taxAmount,
+            $taxRate->isIncludedInPrice()
+        );
+        $unitTaxAdjustment->setDetails([
+            'taxRateCode' => $taxRate->getCode(),
+            'taxRateName' => $taxRate->getName(),
+            'taxRateAmount' => $taxRate->getAmount(),
+        ]);
```
Comment (lchrusciel) [inline src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php:87]: As previously it seems like an obvious candidate to have keys as consts + creation of this structure could be extracted to separate service

File: src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php (hunk 12 above)
Comment (lchrusciel) [reply src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php:32]: The same is true for other applicators, but it is true for all the applicators in pure Sylius as well. We could add final tho IMHO

File: spec/OrderProcessor/OrderTaxesProcessorSpec.php (hunk 2 above)
Comment (GSadee) [reply spec/OrderProcessor/OrderTaxesProcessorSpec.php:64]: It is `shouldBeCalled`, not `willReturn`, I wanted to group it with other `shouldBeCalled` statements.

File: spec/OrderProcessor/OrderTaxesProcessorSpec.php (hunk 3 above)
Comment (GSadee) [reply spec/OrderProcessor/OrderTaxesProcessorSpec.php:113]: As above

File: spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php [hunk 14]
```diff
@@ -0,0 +1,160 @@
...
+    ): void {
+        $this->beConstructedWith($calculator, $adjustmentsFactory, $taxRateResolver);
+    }
+
+    function it_implements_an_order_shipment_taxes_applicator_interface(): void
+    {
+        $this->shouldImplement(OrderTaxesApplicatorInterface::class);
+    }
+
+    function it_applies_shipment_taxes_on_order_based_on_shipment_adjustments_promotions_and_rate(
```
[the remark this answers is not in the document]
Comment (GSadee) [reply spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php:45]: In line: `$order->getShippingTotal()->willReturn(1000);`, but this is sth that is mocked so I've fix the name of this test method

File: src/Migrations/Version20201208105207.php (hunk 10 above)
Comment (GSadee) [reply src/Migrations/Version20201208105207.php:92]: This is a copy-paste migration from [this PR](https://github.com/Sylius/Sylius/pull/12116)

File: src/OrderProcessor/ShippingChargesProcessor.php (hunk 11 above)
Comment (GSadee) [reply src/OrderProcessor/ShippingChargesProcessor.php:58]: I guess that yes, in current implementation we need it because `removeAdjustments` method removes that adjustment only from current entity

File: src/DependencyInjection/SyliusRefundExtension.php (hunk 9 above)
Comment (GSadee) [reply src/DependencyInjection/SyliusRefundExtension.php:49]: We could, but not in this PR imo

File: src/Migrations/Version20201208105207.php (hunk 10 above)
Comment (lchrusciel) [reply src/Migrations/Version20201208105207.php:92]: This may collapse during dry-run execution (ref. https://stackoverflow.com/a/18580775). Can we adjust it to `addSql` in both places?

File: src/Entity/ShipmentTrait.php [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+ * It is a duplication of a logic from Sylius to provide proper adjustments handling.
+ */
+trait ShipmentTrait
+{
+    /**
+     * @var Collection|BaseAdjustmentInterface[]
+     *
+     * @psalm-var Collection<array-key, BaseAdjustmentInterface>
+     */
+
```
Comment (lchrusciel) [inline src/Entity/ShipmentTrait.php:33]:
```suggestion
```

**Review by lchrusciel — APPROVED** [review]

File: UPGRADE.md [hunk 16]
```diff
@@ -1,3 +1,77 @@
...
+ */
+class Shipment extends BaseShipment implements ShipmentInterface
+{
+    use ShipmentTrait;
+
+    public function __construct()
+    {
+        parent::__construct();
+
+        /** @var ArrayCollection<array-key, BaseAdjustmentInterface> $this->adjustments */
```
Comment (lchrusciel) [inline UPGRADE.md:68]: Probably a minor thing, but `BaseAdjustmentInterface` does not exist in the namespaces

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Grzegorz! :1st_place_medal:
