### PR TITLE
[RefundPayment] Change order number to Order relation on RefundPayment

### LINKED ISSUE #193: [RFC] It's not possible to distinguish between refund requests; Incorrect DB design?
Hi,

RefundPlugin doesn't not track refund requests, only result. One may think, that `Entity\Refund` will contain multiple `Entity\RefundUnit` and therefore I will always know which OrderItemUnits were refunded and when, but it's not the case though, `Entity\Refund` is mapped to refunded unit
```
         $this->eventBus->dispatch(new UnitsRefunded(
             $orderNumber,
             $command->units(),
             $command->shipments(),
             $command->paymentMethodId(),
             $refundedTotal,
             $order->getCurrencyCode(),
             $command->comment()
         ));
```

I expect to have some kind of `Entity\RefundGroup/Entity\RefundRequest` with `issuedAt`, which will tie together `Refund`, `RefundPayment` and possibly `CreditMemo`.

It's also strange to me, that `RefundPayment` and `Refund` don't have doctrine relationship (Unidirectional at least) to `Order` and use  `order_number` to manually track the relation, while `CreditMemo` have the doctrine relationship. 
I would expected this to be the other hand around, like [InvoicingPlugin\Invoice](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Entity/Invoice.php) only tracks `orderNumber`

Another point is that `CreditMemo` should be generated only after `RefundPayment` is confirmed. I would guess there are various financial flows, where CreditMemo can be generated before the refund executed, but for simplicity sake it should the same as for Invoice, which is generated only after order is *paid*.

And usage of messenger for `CreditMemo` and not `CreditMemoPdf` is not called for: it will never be executed async and adds complexity of messenger message wrapping, like critical error will be lowered to error level without execution flow stop, therefore overall refund state will be broken without no way of solving it.

### PR DESCRIPTION
**Pull request by GSadee**
Partially fixes #193

Similar to #306

### CODE REVIEW

File: src/ProcessManager/RefundPaymentProcessManager.php [hunk 1]
```diff
@@ -43,20 +49,26 @@ public function __construct(
...
         $this->refundPaymentFactory = $refundPaymentFactory;
+        $this->orderRepository = $orderRepository;
         $this->entityManager = $entityManager;
         $this->eventBus = $eventBus;
     }
 
     public function next(UnitsRefunded $unitsRefunded): void
     {
+        /** @var OrderInterface|null $order */
+        $order = $this->orderRepository->findOneByNumber($unitsRefunded->orderNumber());
```
Comment (GSadee) [inline src/ProcessManager/RefundPaymentProcessManager.php:67]: I wonder if I should find the order here or in `RefundPaymentFactory` 🤔 Especially that we are already finding the payment method by its id in the factory. Wdyt?

Comment (Zales0123) [reply src/ProcessManager/RefundPaymentProcessManager.php:67]: In my opinion, we should pass to the factory as final data as possible, to allow it to create the desired object _and do nothing more_ 🚀

File: src/Resources/config/admin_routing.yml [hunk 2]
```diff
@@ -59,8 +59,8 @@ sylius_refund_order_refund_payment_list:
         _sylius:
             template: "@SyliusRefundPlugin/Order/Admin/RefundPayment/list.html.twig"
             repository:
-                method: findByOrderNumber
-                arguments: $orderNumber
+                method: findByOrder
+                arguments: expr:service('sylius.repository.order').findOneByNumber($orderNumber)
```
Comment (Zales0123) [inline src/Resources/config/admin_routing.yml:63]: I'm not sure about this approach. We're calling the repository to retrieve the object, to pass it to the same repository but another function 💃 maybe we could just introduce a custom repository method that would take the order number and join the orders' table in a query builder?

File: src/Resources/config/services/providers.xml [hunk 3]
```diff
@@ -53,7 +53,6 @@
             id="Sylius\RefundPlugin\Provider\RelatedPaymentIdProviderInterface"
             class="Sylius\RefundPlugin\Provider\DefaultRelatedPaymentIdProvider"
         >
-            <argument type="service" id="sylius.repository.order" />
         </service>
```
Comment (Zales0123) [inline src/Resources/config/services/providers.xml:56]: So it could be shorten:
```xml
<service
   id="Sylius\RefundPlugin\Provider\RelatedPaymentIdProviderInterface"
   class="Sylius\RefundPlugin\Provider\DefaultRelatedPaymentIdProvider"
/>
```

File: src/Resources/config/admin_routing.yml (hunk 2 above)
Comment (GSadee) [reply src/Resources/config/admin_routing.yml:63]: It is not the same repository, I'm calling the order repository to retrieve the order, to pass it to the refund payment repository.
However, introducing a custom repository method is ok for me, I wonder about that, but the above solution was just simpler, but I agree that it was probably the worse option due to performance (2 calls to db instead of 1 with additional join).

Comment (Zales0123) [reply src/Resources/config/admin_routing.yml:63]: Yeah, indeed, these are 2 different repositories xD Sorry, I had a hallucination 💃

**Review by Tomanhez — APPROVED** [review]

**Review by SirDomin — APPROVED** [review]

File: src/Doctrine/ORM/RefundPaymentRepository.php [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\RefundPlugin\Doctrine\ORM;
+
+use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;
+use Sylius\RefundPlugin\Repository\RefundPaymentRepositoryInterface;
+
+class RefundPaymentRepository extends EntityRepository implements RefundPaymentRepositoryInterface
```
Comment (Zales0123) [inline src/Doctrine/ORM/RefundPaymentRepository.php:19]: Should we (similar to factories) provide trait that should be implemented in the repository? But I suppose it's not a case for this change but for all the repositories and plugin 💃

File: src/Doctrine/ORM/RefundPaymentRepository.php [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+{
+    public function findByOrderNumber(string $orderNumber): array
+    {
+        return $this->createQueryBuilder('o')
+            ->innerJoin('o.order', 'ord')
```
Comment (Zales0123) [inline src/Doctrine/ORM/RefundPaymentRepository.php:24]: `ord` 😱 Is it because `order` is a banned name? 😄 maybe then `refundPaymentOrder`?

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thanks, Grzegorz! :tada:

File: src/Doctrine/ORM/RefundPaymentRepository.php (hunk 5 above)
Comment (GSadee) [reply src/Doctrine/ORM/RefundPaymentRepository.php:24]: Yup, that is the reason 😃 And to be honest, it is a copy-pasted shortcut from Sylius, but I agree that `refundPaymentOrder` looks better 😃

File: src/Doctrine/ORM/RefundPaymentRepository.php (hunk 4 above)
Comment (GSadee) [reply src/Doctrine/ORM/RefundPaymentRepository.php:19]: I think so, but this is the plugin, that defines RefundPayment, so creating a repository without traits makes sense here.
